project:
  type: website

website:
  page-navigation: true
  site-url: https://posit-dev.github.io/positron-workshop/
  title: "Getting Started with Positron"
  description: "Half-day introduction to Positron for R/RStudio users"
  image: images/card.png
  repo-url: https://github.com/posit-dev/positron-workshop
  page-footer:
    center:
      - icon: github
        href: https://github.com/posit-dev/positron-workshop
    right: "This page is built with 💙 and [Quarto](https://quarto.org/)."
  open-graph: true
  sidebar:
    id: main
    logo: images/positron-icon.svg
    title: Getting Started with Positron
    pinned: true
    align: center
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: setup.qmd
      - text: "---"
      - auto: modules/
    
format:
  html:
    css: positron-settings.css
    code-overflow: wrap

